version: '3'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: university

volumes:
  dbdata:
